{
  "borgbackup": [],
  "brltty": [],
  "buttermanager": [],
  "cmake": [],
  "collectd": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2317175"
  ],
  "dnf": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323186"
  ],
  "gi-docgen": [],
  "javapackages-tools": [],
  "jello": [],
  "lammps": [],
  "libgpiod": [],
  "libnvme": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325194"
  ],
  "link-grammar": [],
  "linode-cli": [],
  "maturin": [],
  "nwchem": [],
  "osc": [],
  "past-time": [],
  "pcs": [],
  "petsc": [],
  "picard": [],
  "protobuf": [],
  "pygobject3": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325886"
  ],
  "pygsl": [],
  "pyproj": [],
  "pyshp": [],
  "python-APScheduler": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325181"
  ],
  "python-absl-py": [],
  "python-aiokafka": [],
  "python-aiosmtpd": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322718"
  ],
  "python-apsw": [],
  "python-astor": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322712"
  ],
  "python-astroid": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323166"
  ],
  "python-async-lru": [],
  "python-asyncssh": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325445"
  ],
  "python-authlib": [],
  "python-avocado": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325218"
  ],
  "python-awscrt": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322714"
  ],
  "python-backrefs": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325184"
  ],
  "python-beartype": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322721"
  ],
  "python-bids-validator": [],
  "python-billiard": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323167"
  ],
  "python-bottle": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325166"
  ],
  "python-chameleon": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322715"
  ],
  "python-cloudpickle": [],
  "python-cmd2": [],
  "python-colcon-parallel-executor": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325186"
  ],
  "python-colorful": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325168"
  ],
  "python-commoncode": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325197"
  ],
  "python-cssutils": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325223"
  ],
  "python-cysignals": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325457"
  ],
  "python-dataclassy": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325200"
  ],
  "python-dill": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323157"
  ],
  "python-django-compressor": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322719"
  ],
  "python-django-extensions": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325451"
  ],
  "python-docstring-parser": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325441"
  ],
  "python-drgn": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325185"
  ],
  "python-easyprocess": [],
  "python-etcd": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323184"
  ],
  "python-flit": [],
  "python-flufl-bounce": [],
  "python-freeipa": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319660"
  ],
  "python-gevent": [],
  "python-giacpy": [],
  "python-gunicorn": [],
  "python-h5netcdf": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325222"
  ],
  "python-hl7": [],
  "python-humanfriendly": [],
  "python-iniparse": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323164"
  ],
  "python-jaraco-functools": [],
  "python-jaraco-packaging": [],
  "python-josepy": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323171"
  ],
  "python-libarchive-c": [],
  "python-lz4": [],
  "python-m3u8": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325427"
  ],
  "python-mccabe": [],
  "python-msal": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323170"
  ],
  "python-msgspec": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325169"
  ],
  "python-neovim": [],
  "python-nose": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323163"
  ],
  "python-oscrypto": [],
  "python-paramiko": [],
  "python-parso": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325187"
  ],
  "python-pexpect": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325182"
  ],
  "python-pluginlib": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323156"
  ],
  "python-pooch": [],
  "python-precis_i18n": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325183"
  ],
  "python-pulp-glue": [],
  "python-pure-protobuf": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322710"
  ],
  "python-pydantic-core": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325425"
  ],
  "python-pydicom": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325443"
  ],
  "python-pyftpdlib": [],
  "python-pymdown-extensions": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325198"
  ],
  "python-pymeeus": [],
  "python-pymongo": [],
  "python-pypandoc": [],
  "python-pyramid": [],
  "python-pyside6": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325444"
  ],
  "python-pysignals": [],
  "python-pytest-aiohttp": [],
  "python-pytest-split": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325447"
  ],
  "python-pyupgrade": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322713"
  ],
  "python-readability-lxml": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323185"
  ],
  "python-recordclass": [],
  "python-redis": [],
  "python-remoto": [],
  "python-repoze-sphinx-autointerface": [],
  "python-repoze-who": [],
  "python-requests-toolbelt": [],
  "python-rpmfluff": [],
  "python-rstcheck": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322705"
  ],
  "python-ruamel-yaml": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323169"
  ],
  "python-s3transfer": [],
  "python-social-auth-core": [],
  "python-ssh-python": [],
  "python-stdlibs": [],
  "python-surt": [],
  "python-terminado": [],
  "python-toolz": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323168"
  ],
  "python-transaction": [],
  "python-typeguard": [],
  "python-typing-inspect": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325455"
  ],
  "python-uvloop": [],
  "python-valkey": [],
  "python-webscrapbook": [],
  "python-whitenoise": [],
  "python-whoosh": [],
  "python-yappi": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323160"
  ],
  "python-yaql": [],
  "python-zc-lockfile": [],
  "python-zict": [],
  "python-zope-exceptions": [],
  "python-zope-interface": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325170"
  ],
  "python-zope-testing": [],
  "python-zstandard": [],
  "realtime-tests": [],
  "rmol": [],
  "salt": [],
  "satyr": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325452"
  ],
  "syncplay": [],
  "trademgen": [],
  "uv": [],
  "visidata": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325446"
  ],
  "watchman": [],
  "weechat": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322708"
  ],
  "xapian-bindings": [],
  "yt-dlp": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325426"
  ]
}