{
  "alot": [],
  "borgbackup": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2326916"
  ],
  "brltty": [],
  "collectd": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2317175"
  ],
  "did": [],
  "dlib": [],
  "dnf": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323186"
  ],
  "grammalecte": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319629"
  ],
  "hivex": [],
  "lammps": [],
  "lasso": [],
  "libgpiod": [],
  "libnvme": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325194"
  ],
  "link-grammar": [],
  "ntpsec": [],
  "obs-studio": [],
  "openmeeg": [],
  "openvswitch": [],
  "pcs": [],
  "petsc": [],
  "postgresql17": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327967"
  ],
  "protobuf": [],
  "pygobject3": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325886"
  ],
  "pygsl": [],
  "pyserial-asyncio": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327980"
  ],
  "python-aiosmtpd": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322718"
  ],
  "python-astor": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322712"
  ],
  "python-astroid": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323166"
  ],
  "python-async-lru": [],
  "python-asyncssh": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325445"
  ],
  "python-autocommand": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327972"
  ],
  "python-avocado": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325218"
  ],
  "python-awscrt": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322714"
  ],
  "python-backrefs": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325184"
  ],
  "python-beartype": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322721"
  ],
  "python-billiard": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323167"
  ],
  "python-binaryornot": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319640"
  ],
  "python-bowler": [],
  "python-capturer": [],
  "python-cccolutils": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319642"
  ],
  "python-chameleon": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322715"
  ],
  "python-cloudpickle": [],
  "python-cmd2": [],
  "python-colcon-parallel-executor": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325186"
  ],
  "python-colorful": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325168"
  ],
  "python-commoncode": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325197"
  ],
  "python-confuse": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327966"
  ],
  "python-cramjam": [],
  "python-cysignals": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325457"
  ],
  "python-dataclassy": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325200"
  ],
  "python-dill": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323157"
  ],
  "python-django-allauth": [],
  "python-django-compressor": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322719"
  ],
  "python-django-contrib-comments": [],
  "python-django-debreach": [],
  "python-django-filter": [],
  "python-django-mailman3": [],
  "python-djangoql": [],
  "python-docstring-parser": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325441"
  ],
  "python-drgn": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325185"
  ],
  "python-dunamai": [],
  "python-engineio": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327989"
  ],
  "python-epub": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319654"
  ],
  "python-etcd": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323184"
  ],
  "python-events": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319655"
  ],
  "python-falcon": [],
  "python-flask": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327965"
  ],
  "python-flit": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2326226"
  ],
  "python-flufl-bounce": [],
  "python-flufl-i18n": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319659"
  ],
  "python-freecell_solver": [],
  "python-genty": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319661"
  ],
  "python-gevent": [],
  "python-giacpy": [],
  "python-grip": [],
  "python-h2": [],
  "python-h5netcdf": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325222"
  ],
  "python-iniparse": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323164"
  ],
  "python-inject": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327978"
  ],
  "python-irc": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327991"
  ],
  "python-jack-client": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319666"
  ],
  "python-jcconv": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319667"
  ],
  "python-jeepney": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327982"
  ],
  "python-josepy": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323171"
  ],
  "python-lazr-uri": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319676"
  ],
  "python-libarchive-c": [],
  "python-libcst": [],
  "python-mccabe": [],
  "python-msal": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323170"
  ],
  "python-msgspec": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325169"
  ],
  "python-neovim": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2326224"
  ],
  "python-nose": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323163"
  ],
  "python-openidc-client": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319685"
  ],
  "python-opytimark": [],
  "python-oscrypto": [],
  "python-parsel": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319689"
  ],
  "python-parso": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325187"
  ],
  "python-pdfkit": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319690"
  ],
  "python-pdm-backend": [],
  "python-pexpect": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325182"
  ],
  "python-pluginlib": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323156"
  ],
  "python-precis_i18n": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325183"
  ],
  "python-pulp-glue": [],
  "python-pure-protobuf": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322710"
  ],
  "python-pycec": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327973"
  ],
  "python-pyclipper": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319696"
  ],
  "python-pydantic-core": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325425"
  ],
  "python-pydispatcher": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319697"
  ],
  "python-pyemd": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319698"
  ],
  "python-pyftpdlib": [],
  "python-pygit2": [],
  "python-pymdown-extensions": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325198"
  ],
  "python-pymediainfo": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319700"
  ],
  "python-pymeeus": [],
  "python-pypandoc": [],
  "python-pyramid": [],
  "python-pyside6": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325444"
  ],
  "python-pytaglib": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319705"
  ],
  "python-pytesseract": [],
  "python-pytest-django": [],
  "python-pytest-flakes": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319708"
  ],
  "python-pytest-rerunfailures": [],
  "python-pytest-runner": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319709"
  ],
  "python-pytest-split": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325447"
  ],
  "python-pyupgrade": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322713"
  ],
  "python-pyvlx": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327983"
  ],
  "python-reactivex": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327987"
  ],
  "python-readability-lxml": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323185"
  ],
  "python-recordclass": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327968"
  ],
  "python-redis": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2326927"
  ],
  "python-remoto": [],
  "python-repoze-lru": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319711"
  ],
  "python-repoze-who": [],
  "python-requests-toolbelt": [],
  "python-resumable-urlretrieve": [],
  "python-rpmfluff": [],
  "python-rstcheck": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322705"
  ],
  "python-ruamel-yaml": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323169"
  ],
  "python-rx": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327979"
  ],
  "python-s3transfer": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2326933"
  ],
  "python-scantree": [],
  "python-scp": [],
  "python-serpy": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319716"
  ],
  "python-sh": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327986"
  ],
  "python-simplegeneric": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319717"
  ],
  "python-singledispatch": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319718"
  ],
  "python-six": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327971"
  ],
  "python-social-auth-core": [],
  "python-sphinxcontrib-autoprogram": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319720"
  ],
  "python-sphinxcontrib-blockdiag": [],
  "python-sphinxcontrib-seqdiag": [],
  "python-sqlalchemy1.4": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327976"
  ],
  "python-ssh-python": [],
  "python-surt": [],
  "python-svg-path": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319725"
  ],
  "python-tenacity": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327977"
  ],
  "python-terminado": [],
  "python-tgscheduler": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319728"
  ],
  "python-throttler": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327988"
  ],
  "python-toolz": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323168"
  ],
  "python-tornado": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327969"
  ],
  "python-tpm2-pytss": [],
  "python-transaction": [],
  "python-translationstring": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319730"
  ],
  "python-tree-format": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319731"
  ],
  "python-txaio": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327981"
  ],
  "python-typeguard": [],
  "python-typing-inspect": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325455"
  ],
  "python-urwid": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2327984"
  ],
  "python-uvloop": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2326210"
  ],
  "python-valkey": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2326934"
  ],
  "python-webscrapbook": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2326915"
  ],
  "python-xunitparser": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319738"
  ],
  "python-yappi": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2323160"
  ],
  "python-zc-lockfile": [],
  "python-zict": [],
  "python-zope-deprecation": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319742"
  ],
  "python-zope-interface": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325170"
  ],
  "python-zope-testing": [],
  "python-zstandard": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2326925"
  ],
  "python3-mallard-ducktype": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319747"
  ],
  "qpid-proton": [],
  "realtime-tests": [],
  "rmol": [],
  "rrdtool": [],
  "ruff": [],
  "satyr": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325452"
  ],
  "sentencepiece": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2319749"
  ],
  "trademgen": [],
  "visidata": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2325446"
  ],
  "watchman": [],
  "weechat": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2322708"
  ]
}