{
  "Mayavi": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2300546",
    "https://bugzilla.redhat.com/show_bug.cgi?id=2291477"
  ],
  "blender": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2291492"
  ],
  "python-datadog": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2290567"
  ],
  "python-jnius": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2272966"
  ],
  "python-ufo2ft": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2301217",
    "https://bugzilla.redhat.com/show_bug.cgi?id=2291961"
  ],
  "python-x2go": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2301218"
  ],
  "xonsh": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2283616"
  ]
}